Repository Niraj-1729/Hacktoberfest, pull requests merged in 2023-10, with the labels that each got.

#6 Space added successfully
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted

#14 added parallax website by me
  .DS_Store
  parallax_effect/.DS_Store
  parallax_effect/assets/2222765.jpg
  parallax_effect/assets/Untitled design.png
  parallax_effect/assets/angry.png
  parallax_effect/assets/bojack1.jpg
  parallax_effect/assets/bojack2.jpg
  parallax_effect/assets/robot.png
  parallax_effect/assets/rr.jpg
  parallax_effect/assets/rr2.jpg
  parallax_effect/assets/truman.jpg
  parallax_effect/index.html
  parallax_effect/main.css
Labels: hacktoberfest, hacktoberfest-accepted

#19 added navbar
  parallax_effect/index.html
  parallax_effect/main.css
Labels: hacktoberfest, hacktoberfest-accepted

#23 Enhance footer
  parallax_effect/index.html
  parallax_effect/main.css
Labels: hacktoberfest, hacktoberfest-accepted

#20 updated UI of parallax_effect
  parallax_effect/main.css
Labels: hacktoberfest, hacktoberfest-accepted

#26 Added Advice-generator folder
  Advice-Generator/.gitignore
  Advice-Generator/README.md
  Advice-Generator/package-lock.json
  Advice-Generator/package.json
  Advice-Generator/public/favicon.ico
  Advice-Generator/public/index.html
  Advice-Generator/public/logo192.png
  Advice-Generator/public/logo512.png
  Advice-Generator/public/manifest.json
  Advice-Generator/public/robots.txt
  Advice-Generator/src/App.css
  Advice-Generator/src/App.js
  Advice-Generator/src/App.test.js
  Advice-Generator/src/img/motivational.jpg
  Advice-Generator/src/index.css
  Advice-Generator/src/index.js
  Advice-Generator/src/logo.svg
  Advice-Generator/src/reportWebVitals.js
  Advice-Generator/src/setupTests.js
Labels: hacktoberfest, hacktoberfest-accepted

#32 Documentation correction
  Advice-Generator/README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#34 Responsive Gym Website
  Gym website/index.html
Labels: hacktoberfest

#38 added path finder to automatically detect the shortest path to a dest…
  PathFinder/aivan2798/anime.css
  PathFinder/aivan2798/index.html
  PathFinder/aivan2798/keys.js
  PathFinder/aivan2798/script.js
  PathFinder/aivan2798/styles.css
  PathFinder/aivan2798/utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#37 rock
  Rock-Paper-Scissors/rock-paper-scissors.html
Labels: hacktoberfest, hacktoberfest-accepted

#31 Event Organizing Website
  Event organizing/background.jpeg
  Event organizing/index.html
  Event organizing/main.css
  Event organizing/main.js
  Event organizing/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#36 added Restaurant website (Hacktoberfest)
  Restaurant Website/.gitignore
  Restaurant Website/README.md
  Restaurant Website/package-lock.json
  Restaurant Website/package.json
  Restaurant Website/public/favicon.ico
  Restaurant Website/public/image/food.jpg
  Restaurant Website/public/image/food1.jpg
  Restaurant Website/public/image/food2.jpg
  Restaurant Website/public/image/logo.png
  Restaurant Website/public/image/person.jpg
  Restaurant Website/public/image/resto.jpg
  Restaurant Website/public/index.html
  Restaurant Website/public/logo192.png
  Restaurant Website/public/logo512.png
  Restaurant Website/public/manifest.json
  Restaurant Website/public/robots.txt
  Restaurant Website/src/App.css
  Restaurant Website/src/App.js
  Restaurant Website/src/App.test.js
  Restaurant Website/src/components/Aboutus.js
  Restaurant Website/src/components/Chefs.js
  Restaurant Website/src/components/Contact.js
  Restaurant Website/src/components/Footer.js
  Restaurant Website/src/components/Intro.js
  Restaurant Website/src/components/Menu.js
  Restaurant Website/src/components/Navbar.js
  Restaurant Website/src/components/Weekspecial.js
  Restaurant Website/src/components/style.css
  Restaurant Website/src/index.css
  Restaurant Website/src/index.js
  Restaurant Website/src/logo.svg
  Restaurant Website/src/reportWebVitals.js
  Restaurant Website/src/setupTests.js
Labels: hacktoberfest, hacktoberfest-accepted

#33 travel template website added hacktoberfest
  Travel Template/about.html
  Travel Template/appimages/9e50cb94-7a34-4c77-b798-3740aff4d45a.png
  Travel Template/appimages/boat_title_icons.png
  Travel Template/assets/background.jpeg
  Travel Template/assets/boat_harbor_sea.jpeg
  Travel Template/assets/goodbackhome.jpeg
  Travel Template/assets/hawai.jpeg
  Travel Template/assets/homeback.png
  Travel Template/assets/left_side_img.jpeg
  Travel Template/assets/nicecard.jpeg
  Travel Template/assets/sanfriancso.jpeg
  Travel Template/assets/switer.jpeg
  Travel Template/assets/tour.jpeg
  Travel Template/discover.html
  Travel Template/index.html
  Travel Template/index.js
  Travel Template/places.html
  Travel Template/styles/about.css
  Travel Template/styles/discover.css
  Travel Template/styles/index.css
  Travel Template/styles/places.css
  Travel Template/trial.html
Labels: hacktoberfest, hacktoberfest-accepted

#46 TODO list web app using html,css and javascript
  TODO_List/index.css
  TODO_List/index.html
  TODO_List/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#49 added portfolio
  portfolio/Photos/bonaparte.jpg
  portfolio/Photos/gitHub.png
  portfolio/Photos/headerLogo.png
  portfolio/Photos/insta.jpg
  portfolio/Photos/linkedin.png
  portfolio/Photos/mal.png
  portfolio/Photos/weatherApp.jpg
  portfolio/README.md
  portfolio/index.html
  portfolio/stylesheet.css
Labels: hacktoberfest, hacktoberfest-accepted

#50 I have Added the web calendar project to this.
  Web Calendar/aboutus.html
  Web Calendar/forgetpass.css
  Web Calendar/forgetpassword.html
  Web Calendar/holidaylist.html
  Web Calendar/homestyle.css
  Web Calendar/index.html
  Web Calendar/login.html
  Web Calendar/loginstyle.css
  Web Calendar/main.js
  Web Calendar/registration.html
  Web Calendar/registrationstyle.css
Labels: hacktoberfest, hacktoberfest-accepted

#54 modern-chair/feature
  Modern-chair/images/chair1.png
  Modern-chair/images/chair2.png
  Modern-chair/images/chair3.png
  Modern-chair/images/chair4.png
  Modern-chair/images/chair5.png
  Modern-chair/images/chair6.png
  Modern-chair/images/color1.jpg
  Modern-chair/images/color2.jpg
  Modern-chair/images/color3.jpg
  Modern-chair/images/color4.jpg
  Modern-chair/images/color5.jpg
  Modern-chair/images/color6.jpg
  Modern-chair/images/favicon.ico
  Modern-chair/index.html
  Modern-chair/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#55 Add files via upload
  Social_website.github.io-main/4.jpg
  Social_website.github.io-main/README.md
  Social_website.github.io-main/allinonebg.jpg
  Social_website.github.io-main/amazonbackground.jpg
  Social_website.github.io-main/amazonlogo.jpg
  Social_website.github.io-main/bg1.jpg
  Social_website.github.io-main/bg2.jpg
  Social_website.github.io-main/chapgpticon.png
  Social_website.github.io-main/chat.png
  Social_website.github.io-main/chatgpt.webp
  Social_website.github.io-main/example.css
  Social_website.github.io-main/example.html
  Social_website.github.io-main/facebook.jpg
  Social_website.github.io-main/facebook.png
  Social_website.github.io-main/first.css
  Social_website.github.io-main/first.html
  Social_website.github.io-main/github.jpg
  Social_website.github.io-main/github1.png
  Social_website.github.io-main/githublogo.webp
  Social_website.github.io-main/githublogo1.png
  Social_website.github.io-main/google.css
  Social_website.github.io-main/google.html
  Social_website.github.io-main/google.webp
  Social_website.github.io-main/googlebackground.jpg
  Social_website.github.io-main/index.html
  Social_website.github.io-main/index1.html
  Social_website.github.io-main/instagram.png
  Social_website.github.io-main/instagrambackground.png
  Social_website.github.io-main/linkdein.png
  Social_website.github.io-main/linkdeinicon.jpeg
  Social_website.github.io-main/linkdeinlogo.png
  Social_website.github.io-main/second.webp
  Social_website.github.io-main/style.css
  Social_website.github.io-main/style1.css
  Social_website.github.io-main/telegrambackground.png
  Social_website.github.io-main/telegramlogo.webp
  Social_website.github.io-main/twitter.png
  Social_website.github.io-main/twitterbackground.avif
  Social_website.github.io-main/whatsaap.jpg
  Social_website.github.io-main/whatsaap.png
  Social_website.github.io-main/wikipedia.png
  Social_website.github.io-main/wikipediabackground.jpg
  Social_website.github.io-main/youtubebackground.jpg
  Social_website.github.io-main/youtubelogo.png
Labels: hacktoberfest, hacktoberfest-accepted

#57 Update index.html
  parallax_effect/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#65 AddLanguageTranslator
  Language Translator/index.html
  Language Translator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#68 Added a QuizApp
  QuizApp/Parth4git/index.html
  QuizApp/Parth4git/script.js
  QuizApp/Parth4git/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#70 Updated BMI Calculator
  .vscode/settings.json
  BMI Calculator/bg_b.jpg
  BMI Calculator/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#75 Shantanu
  parallax_effect/index.html
  parallax_effect/main.css
Labels: hacktoberfest, hacktoberfest-accepted

#76 Enhance footer in project inside the folder :- Parallax_effect #15
  parallax_effect/main.css
Labels: hacktoberfest, hacktoberfest-accepted
